[tools]
node = "24"
java = "25"
python = "latest"
go = "1.25"
rust = "stable"
maven = "latest"
gradle = "latest"
"npm:@openai/codex" = "latest"
"npm:@steipete/oracle" = "latest"
"npm:@github/copilot-language-server" = "latest"
"pipx:youtrack-cli" = "latest"
"npm:warelay" = "latest"
"npm:happy-coder" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"
"npm:tsx" = "latest"
"npm:openclaw" = "latest"
"npm:ts-node" = "latest"
"npm:bun" = "latest"

[env]
NPM_CONFIG_IGNORE_PSCRIPTS = "true"
